name: PR Tests
on: 
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      [pipfile-experiment,readme-update2]
  workflow_dispatch: {}


jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v4
      - name: Install Python, pipenv and Pipfile packages
        uses: kojoru/prepare-pipenv@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Turn on 'editable' mode
        run: |
          pipenv install -e .
      - name: Test with pytest
        run: |
          pipenv install pytest
          pipenv --venv
          pipenv run python -m pytest
